server:
  port: 80
spring:
  view:
    suffix: .html
    prefix: /
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/power?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: dk990807
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

